apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: backend-tests-go-sgbmaxll
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backend-tests-go-sgbmaxll 
  name: backend-tests-go-sgbmaxll
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: backend-tests-go-sgbmaxll 
